### ISSUE TITLE
ERROR: unexpected character

### ISSUE THREAD

**Issue by mezianeAITE** [Aluriak/grammar-boolean-rapsody#1]
Dear great Aluriak,

I tried to use G-B-R but i'm faced with the following error:
ERROR: unexpected character

Here is the string i'm working on:
string = '(b10648 and b1064 and (b2675 or b2676)) or (b3610 and (b2675 and b2676)) or (b1654 or (b2675 and b2676))'

I changed in the __main__:
The string to test and the operators
OP_AND = 'and'
OP_OR  = 'or'

This is the exact error:
ERROR: unexpected character at position 7 (prev: Type.Other ; curr: Type.Other )
	 (b10648 and b1064 and (b2675 or b2676)) or (b3610 and (b2675 and b2676)) or (b1654 or (b2675 and b2676))

Thanks for your help :D
Meziane

**Comment by mezianeAITE** [comment]
Edit: fixed, the error cames from the presence of whitespace characters.
But i still can't handle this one: '((b2417&b1101&b2415&b2416)|(b0679))'
I'm expecting : [('b2417', 'b1101', 'b2415', 'b2416'), ('b0679)'] but i only have  [('b2417', 'b1101', 'b2415', 'b2416')]

And this simple one is not handled '(b2417|b0679)' 

>   (...)
 assert len(root) == 1
AssertionError

Thanks
Meziane

**Comment by Aluriak** [comment]
Hi Meziane !

Sorry i didn't come here earlier ; glad you find the problem.

As said [in doc](https://github.com/Aluriak/grammar-boolean-rapsody/blob/master/__main__.py#L46), GBR do not handle motives starting with multiple roots, including `a&b`, or the one you give.

A simple workaround could be to include all your expressions in `_&(<your expressions>)`, having thus only one root named `_`.

I will work on a proper implementation of the problem, so this corner case (and some others) will not appear. Performance gain are also probable.

I will close this issue ; stay tunned for further implementation details.
